Выполнены задачи 2-й лабораторной работы
avalon-dev-j110/laboratornaya-rabota-no2-Isakov11 pull request #1
Opened 2020-03-28 19:37 UTC by Isakov11

Прошу проверить 2-ю лабораторную работу.

2020-04-05 19:41 UTC, KolosovKD requested changes

2020-04-05 19:41 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/Application.java
> +    static Shape MaxArea(Shape Shapes[]){
название метода должно начинаться с маленькой буквы

2020-04-05 19:41 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/Application.java
> +        }
используйте проверку на null вместо обаботки исключения.

2020-04-08 09:16 UTC, Isakov11 commented
Поправил метод maxArea
Реквест на проверку

2020-04-08 21:39 UTC, KolosovKD commented
А зачем вы добавили метод  _**getRotation**_?

2020-04-08 21:39 UTC, merged

2020-04-13 09:07 UTC, Isakov11 commented
А зачем вы добавили метод getRotation?
>> Делал лабораторную на основе форка Lab-2. В ней было задание на этот метод